<?php
include 'config.php';
require_once 'vendor/autoload.php'; // Require Composer's autoloader for dompdf

use Dompdf\Dompdf;

if (!isset($_SESSION['user_id'])) {
    header('Location: login.php');
    exit();
}

// Get all projects with client information
$query = "SELECT p.*, c.name as client_name, c.email as client_email, c.phone as client_phone 
          FROM projects p LEFT JOIN clients c ON p.client_id = c.id";
$stmt = $pdo->query($query);
$projects = $stmt->fetchAll();

// HTML content for PDF
$html = '
<!DOCTYPE html>
<html>
<head>
    <title>Project Status Report</title>
    <style>
        body { font-family: Arial, sans-serif; }
        h1 { color: #333; text-align: center; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        th { background-color: #f2f2f2; }
        .status-completed { color: #28a745; }
        .status-in-progress { color: #ffc107; }
        .status-not-started { color: #6c757d; }
        .status-on-hold { color: #dc3545; }
        .footer { margin-top: 30px; font-size: 12px; text-align: center; color: #6c757d; }
    </style>
</head>
<body>
    <h1>Project Status Report</h1>
    <p><strong>Generated on:</strong> ' . date('F j, Y') . '</p>
    <p><strong>Generated by:</strong> ' . $_SESSION['username'] . ' (' . $_SESSION['role'] . ')</p>
    
    <table>
        <thead>
            <tr>
                <th>Project Name</th>
                <th>Client</th>
                <th>Start Date</th>
                <th>End Date</th>
                <th>Status</th>
                <th>Payment</th>
                <th>Notes</th>
            </tr>
        </thead>
        <tbody>';

foreach ($projects as $project) {
    $html .= '
            <tr>
                <td>' . htmlspecialchars($project['name']) . '</td>
                <td>' . htmlspecialchars($project['client_name'] ?? 'N/A') . '</td>
                <td>' . ($project['start_date'] ?? 'Not set') . '</td>
                <td>' . ($project['end_date'] ?? 'Not set') . '</td>
                <td class="status-' . strtolower(str_replace(' ', '-', $project['status'])) . '">' . $project['status'] . '</td>
                <td>' . $project['payment_status'] . '</td>
                <td>' . htmlspecialchars($project['notes'] ?? '') . '</td>
            </tr>';
}

$html .= '
        </tbody>
    </table>
    
    <div class="footer">
        <p>Status Key: 
            <span class="status-completed">Completed</span> | 
            <span class="status-in-progress">In Progress</span> | 
            <span class="status-not-started">Not Started</span> | 
            <span class="status-on-hold">On Hold</span>
        </p>
    </div>
</body>
</html>';

// Generate PDF
$dompdf = new Dompdf();
$dompdf->loadHtml($html);
$dompdf->setPaper('A4', 'landscape');
$dompdf->render();

// Output the generated PDF to browser
$dompdf->stream("project_status_report.pdf", [
    "Attachment" => true
]);
?>